on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Set up WireMock as a standalone process
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Action E2E Test
        uses: ./
        id: setup-wiremock
        with:
          mappings: 'example-mapping-directory'
          files: 'example-files-directory'
        continue-on-error: true
      - name: Get the WireMock standard output
        run: echo "${{ steps.setup-wiremock.outputs.wiremock-stdout }}"
      - name: Get the WireMock standard error
        run: echo "${{ steps.setup-wiremock.outputs.wiremock-stderr }}"